In [5]:
import pandas as pd
import re
from sklearn.metrics import classification_report
import joblib
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [6]:
fake = pd.read_csv("Fake.csv")
real = pd.read_csv("True.csv")

In [7]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [8]:
real.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [9]:
fake["class"] = 0
real["class"] = 1

In [10]:
data = pd.concat ([fake,real] , axis= 0)

In [11]:
data.sample(10)

,title,text,subject,date,class
9295,U.S. election's anti-trade tone 'concerning': ...,NEW YORK (Reuters) - Rhetoric against free tra...,politicsNews,"June 2, 2016",1
12169,KELLYANNE CONWAY Responds To DEATH THREATS Aga...,Donald Trump s campaign manager Kellyanne Conw...,politics,"Dec 11, 2016",0
18215,Saudi Arabia says it dismantles Islamic State ...,RIYADH (Reuters) - Saudi Arabia said on Thursd...,worldnews,"October 5, 2017",1
20198,EU should enforce rules to prevent vetoes on t...,STRASBOURG (Reuters) - Tax reforms in the Euro...,worldnews,"September 13, 2017",1
14645,Iran factions use earthquake relief effort to ...,ANKARA (Reuters) - Political infighting among ...,worldnews,"November 16, 2017",1
8555,Trump ally Christie calls criticisms of slain ...,"WASHINGTON (Reuters) - Chris Christie, a close...",politicsNews,"August 2, 2016",1
2663,WATCH: Joe Scarborough Fears Trump Will Murde...,Donald Trump s admiration of Vladimir Putin an...,News,"February 6, 2017",0
12148,GEORGE STEPHANOPOULOS’ Wife Tells ‘The View’ T...,,politics,"Dec 14, 2016",0
15075,North Korea says Trump begged for a war during...,SEOUL (Reuters) - North Korea said on Saturday...,worldnews,"November 11, 2017",1
7777,Family Values Republican Bill O’Reilly Loses ...,Fox News host Bill O Reilly finally lost a yea...,News,"February 29, 2016",0

In [12]:
data.columns = data.columns.str.strip()
columns_to_drop = ["title", "subject", "date"]
data.drop(columns=[col for col in columns_to_drop if col in data.columns], inplace=True)

In [13]:
data.sample(10)

                                                    text  class
11477  I simply put together the stories that YOUR pr...      0
13715  This is a rare moment of uncomfortable questio...      0
21965  What this story shows is that while there are ...      0
13220  RIYADH (Reuters) - Saudi Arabia has invited U....      1
7153   Paul Lepage, the Tea Party disaster that happe...      0
8661   We all know that the only reason Donald Trump ...      0
20143  Dan Rather just released a Facebook post that ...      0
22074  USA Meg Mall in Seattle, WA (Source: Bynyalcin...      0
10569  What in the world is wrong with these press pe...      0
15419  SEOUL (Reuters) - After months of fiery rhetor...      1

In [14]:
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\[\]', "", text)  # Remove empty brackets
    text = re.sub(r"https?://\S+|www\.\S+", "", text)  # Remove URLs
    text = re.sub(r"<.*?>", "", text)  # Remove HTML tags
    text = re.sub(r"[%s]" % re.escape(string.punctuation), "", text)  # Remove punctuation
    text = re.sub(r"\n", "", text)  # Remove newlines
    text = re.sub(r"\w*\d\w*", "", text)  # Remove words containing digits
    return text  # Return the cleaned text

In [15]:
data["text"] = data["text"].apply(clean_text)

In [16]:
x = data["text"]
y = data["class"]

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.25 , random_state=42)

In [17]:
vectorizer =  TfidfVectorizer()
xv_train = vectorizer.fit_transform(x_train)
xv_test = vectorizer.transform(x_test)

In [18]:
lr = LogisticRegression()
lr.fit(xv_train , y_train)

LogisticRegression()

In [19]:
prediction = lr.predict(xv_test)
lr.score(xv_test,y_test)

0.986369710467706

In [20]:


x = data["text"]
y = data["class"]

x = data["text"]
y = data["class"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)


vectorizer = CountVectorizer(stop_words='english')  
X_train = vectorizer.fit_transform(x_train)  
X_test = vectorizer.transform(x_test)        


nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)  


y_pred = nb_model.predict(X_test)

nb_accuracy = accuracy_score(y_test, y_pred)
print(f'Naive Bayes Accuracy: {nb_accuracy:.2f}')

nb_score = nb_model.score(X_test, y_test)
print(f'Naive Bayes Score: {nb_score:.2f}')

Naive Bayes Accuracy: 0.95
Naive Bayes Score: 0.95

In [22]:

x = data["text"]
y = data["class"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

vectorizer = TfidfVectorizer(stop_words='english') 
xv_train = vectorizer.fit_transform(x_train)  
xv_test = vectorizer.transform(x_test)       

rf_model = RandomForestClassifier(random_state=42)  
rf_model.fit(xv_train, y_train)  


rf_accuracy = rf_model.score(xv_test, y_test)  
print(f'Random Forest Accuracy: {rf_accuracy:.2f}')


y_pred = rf_model.predict(xv_test)

print("Classification Report:")
print(classification_report(y_test, y_pred))

KeyboardInterrupt:

In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from sklearn.metrics import accuracy_score, classification_report


fake = pd.read_csv("Fake.csv")
real = pd.read_csv("True.csv")


fake["class"] = 0
real["class"] = 1


data = pd.concat([fake, real], axis=0)


x = data["text"]
y = data["class"]


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)


tokenizer = Tokenizer()
tokenizer.fit_on_texts(x_train)  
x_train_seq = tokenizer.texts_to_sequences(x_train)
x_test_seq = tokenizer.texts_to_sequences(x_test)


max_length = max(len(seq) for seq in x_train_seq) 
x_train_padded = pad_sequences(x_train_seq, maxlen=max_length)
x_test_padded = pad_sequences(x_test_seq, maxlen=max_length)


vocab_size = len(tokenizer.word_index) + 1 
embedding_dim = 100  

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim))  
model.add(LSTM(128))  
model.add(Dense(1, activation='sigmoid'))  

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()  

model.fit(x_train_padded, y_train, validation_split=0.1, epochs=1, batch_size=32, verbose=0)


y_pred_prob = model.predict(x_test_padded)
y_pred = (y_pred_prob > 0.5).astype(int)  


lstm_accuracy = accuracy_score(y_test, y_pred)
print(f'LSTM Accuracy: {lstm_accuracy:.2f}')


print("Classification Report:")
print(classification_report(y_test, y_pred))


print("\nFirst 10 Predictions vs True Labels:")
for i in range(10):
    print(f"Predicted: {y_pred[i][0]}, True: {y_test.iloc[i]}")

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

KeyboardInterrupt:

In [31]:
joblib.dump(vectorizer, "vectorizer.jb")
joblib.dump(lr,"lr_model.jb")
joblib.dump(rf_model,"rf_mod.jb")
joblib.dump(nb_model,"nb_mod.jb")
joblib.dump(model,"lstm.jb")

['lstm.jb']